name: "Build UserInterface"

permissions:
  contents: write
  discussions: write

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          architecture: "x64"
          cache: "pip"
      - name: Build tool
        run: |
          python build.py
      - name: Upload Win Build
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: TIK-win
          path: "./TIK-win.zip"

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          architecture: "x64"
          cache: "pip"
      - name: Build UserInterface
        run: |
          python3 build.py
      - name: Upload Linux Build
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: TIK-linux
          path: "./TIK-linux.zip"
